name: flutter_dynamic_translator
description: A Flutter project for dynamic translations.

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  assets:
    - assets/lang/
